# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MonsterHitPoints(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, average: int=None, formula: str=None):  # noqa: E501
        """MonsterHitPoints - a model defined in Swagger

        :param average: The average of this MonsterHitPoints.  # noqa: E501
        :type average: int
        :param formula: The formula of this MonsterHitPoints.  # noqa: E501
        :type formula: str
        """
        self.swagger_types = {
            'average': int,
            'formula': str
        }

        self.attribute_map = {
            'average': 'average',
            'formula': 'formula'
        }
        self._average = average
        self._formula = formula

    @classmethod
    def from_dict(cls, dikt) -> 'MonsterHitPoints':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Monster_hitPoints of this MonsterHitPoints.  # noqa: E501
        :rtype: MonsterHitPoints
        """
        return util.deserialize_model(dikt, cls)

    @property
    def average(self) -> int:
        """Gets the average of this MonsterHitPoints.


        :return: The average of this MonsterHitPoints.
        :rtype: int
        """
        return self._average

    @average.setter
    def average(self, average: int):
        """Sets the average of this MonsterHitPoints.


        :param average: The average of this MonsterHitPoints.
        :type average: int
        """

        self._average = average

    @property
    def formula(self) -> str:
        """Gets the formula of this MonsterHitPoints.


        :return: The formula of this MonsterHitPoints.
        :rtype: str
        """
        return self._formula

    @formula.setter
    def formula(self, formula: str):
        """Sets the formula of this MonsterHitPoints.


        :param formula: The formula of this MonsterHitPoints.
        :type formula: str
        """

        self._formula = formula
