# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.character_attributes import CharacterAttributes  # noqa: F401,E501
from swagger_server import util


class NPC(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, npc_name: str=None, role: str=None, alignment: str=None, race: str=None, attributes: CharacterAttributes=None, hit_points: int=None, armor_class: int=None, skills: Dict[str, int]=None, languages: str=None, equipment: List[str]=None, background: str=None, personality_traits: str=None, ideals: str=None, bonds: str=None, flaws: str=None):  # noqa: E501
        """NPC - a model defined in Swagger

        :param npc_name: The npc_name of this NPC.  # noqa: E501
        :type npc_name: str
        :param role: The role of this NPC.  # noqa: E501
        :type role: str
        :param alignment: The alignment of this NPC.  # noqa: E501
        :type alignment: str
        :param race: The race of this NPC.  # noqa: E501
        :type race: str
        :param attributes: The attributes of this NPC.  # noqa: E501
        :type attributes: CharacterAttributes
        :param hit_points: The hit_points of this NPC.  # noqa: E501
        :type hit_points: int
        :param armor_class: The armor_class of this NPC.  # noqa: E501
        :type armor_class: int
        :param skills: The skills of this NPC.  # noqa: E501
        :type skills: Dict[str, int]
        :param languages: The languages of this NPC.  # noqa: E501
        :type languages: str
        :param equipment: The equipment of this NPC.  # noqa: E501
        :type equipment: List[str]
        :param background: The background of this NPC.  # noqa: E501
        :type background: str
        :param personality_traits: The personality_traits of this NPC.  # noqa: E501
        :type personality_traits: str
        :param ideals: The ideals of this NPC.  # noqa: E501
        :type ideals: str
        :param bonds: The bonds of this NPC.  # noqa: E501
        :type bonds: str
        :param flaws: The flaws of this NPC.  # noqa: E501
        :type flaws: str
        """
        self.swagger_types = {
            'npc_name': str,
            'role': str,
            'alignment': str,
            'race': str,
            'attributes': CharacterAttributes,
            'hit_points': int,
            'armor_class': int,
            'skills': Dict[str, int],
            'languages': str,
            'equipment': List[str],
            'background': str,
            'personality_traits': str,
            'ideals': str,
            'bonds': str,
            'flaws': str
        }

        self.attribute_map = {
            'npc_name': 'npcName',
            'role': 'role',
            'alignment': 'alignment',
            'race': 'race',
            'attributes': 'attributes',
            'hit_points': 'hitPoints',
            'armor_class': 'armorClass',
            'skills': 'skills',
            'languages': 'languages',
            'equipment': 'equipment',
            'background': 'background',
            'personality_traits': 'personalityTraits',
            'ideals': 'ideals',
            'bonds': 'bonds',
            'flaws': 'flaws'
        }
        self._npc_name = npc_name
        self._role = role
        self._alignment = alignment
        self._race = race
        self._attributes = attributes
        self._hit_points = hit_points
        self._armor_class = armor_class
        self._skills = skills
        self._languages = languages
        self._equipment = equipment
        self._background = background
        self._personality_traits = personality_traits
        self._ideals = ideals
        self._bonds = bonds
        self._flaws = flaws

    @classmethod
    def from_dict(cls, dikt) -> 'NPC':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NPC of this NPC.  # noqa: E501
        :rtype: NPC
        """
        return util.deserialize_model(dikt, cls)

    @property
    def npc_name(self) -> str:
        """Gets the npc_name of this NPC.


        :return: The npc_name of this NPC.
        :rtype: str
        """
        return self._npc_name

    @npc_name.setter
    def npc_name(self, npc_name: str):
        """Sets the npc_name of this NPC.


        :param npc_name: The npc_name of this NPC.
        :type npc_name: str
        """
        if npc_name is None:
            raise ValueError("Invalid value for `npc_name`, must not be `None`")  # noqa: E501

        self._npc_name = npc_name

    @property
    def role(self) -> str:
        """Gets the role of this NPC.


        :return: The role of this NPC.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role: str):
        """Sets the role of this NPC.


        :param role: The role of this NPC.
        :type role: str
        """
        if role is None:
            raise ValueError("Invalid value for `role`, must not be `None`")  # noqa: E501

        self._role = role

    @property
    def alignment(self) -> str:
        """Gets the alignment of this NPC.


        :return: The alignment of this NPC.
        :rtype: str
        """
        return self._alignment

    @alignment.setter
    def alignment(self, alignment: str):
        """Sets the alignment of this NPC.


        :param alignment: The alignment of this NPC.
        :type alignment: str
        """
        if alignment is None:
            raise ValueError("Invalid value for `alignment`, must not be `None`")  # noqa: E501

        self._alignment = alignment

    @property
    def race(self) -> str:
        """Gets the race of this NPC.


        :return: The race of this NPC.
        :rtype: str
        """
        return self._race

    @race.setter
    def race(self, race: str):
        """Sets the race of this NPC.


        :param race: The race of this NPC.
        :type race: str
        """
        if race is None:
            raise ValueError("Invalid value for `race`, must not be `None`")  # noqa: E501

        self._race = race

    @property
    def attributes(self) -> CharacterAttributes:
        """Gets the attributes of this NPC.


        :return: The attributes of this NPC.
        :rtype: CharacterAttributes
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: CharacterAttributes):
        """Sets the attributes of this NPC.


        :param attributes: The attributes of this NPC.
        :type attributes: CharacterAttributes
        """
        if attributes is None:
            raise ValueError("Invalid value for `attributes`, must not be `None`")  # noqa: E501

        self._attributes = attributes

    @property
    def hit_points(self) -> int:
        """Gets the hit_points of this NPC.


        :return: The hit_points of this NPC.
        :rtype: int
        """
        return self._hit_points

    @hit_points.setter
    def hit_points(self, hit_points: int):
        """Sets the hit_points of this NPC.


        :param hit_points: The hit_points of this NPC.
        :type hit_points: int
        """
        if hit_points is None:
            raise ValueError("Invalid value for `hit_points`, must not be `None`")  # noqa: E501

        self._hit_points = hit_points

    @property
    def armor_class(self) -> int:
        """Gets the armor_class of this NPC.


        :return: The armor_class of this NPC.
        :rtype: int
        """
        return self._armor_class

    @armor_class.setter
    def armor_class(self, armor_class: int):
        """Sets the armor_class of this NPC.


        :param armor_class: The armor_class of this NPC.
        :type armor_class: int
        """
        if armor_class is None:
            raise ValueError("Invalid value for `armor_class`, must not be `None`")  # noqa: E501

        self._armor_class = armor_class

    @property
    def skills(self) -> Dict[str, int]:
        """Gets the skills of this NPC.


        :return: The skills of this NPC.
        :rtype: Dict[str, int]
        """
        return self._skills

    @skills.setter
    def skills(self, skills: Dict[str, int]):
        """Sets the skills of this NPC.


        :param skills: The skills of this NPC.
        :type skills: Dict[str, int]
        """

        self._skills = skills

    @property
    def languages(self) -> str:
        """Gets the languages of this NPC.


        :return: The languages of this NPC.
        :rtype: str
        """
        return self._languages

    @languages.setter
    def languages(self, languages: str):
        """Sets the languages of this NPC.


        :param languages: The languages of this NPC.
        :type languages: str
        """

        self._languages = languages

    @property
    def equipment(self) -> List[str]:
        """Gets the equipment of this NPC.


        :return: The equipment of this NPC.
        :rtype: List[str]
        """
        return self._equipment

    @equipment.setter
    def equipment(self, equipment: List[str]):
        """Sets the equipment of this NPC.


        :param equipment: The equipment of this NPC.
        :type equipment: List[str]
        """

        self._equipment = equipment

    @property
    def background(self) -> str:
        """Gets the background of this NPC.


        :return: The background of this NPC.
        :rtype: str
        """
        return self._background

    @background.setter
    def background(self, background: str):
        """Sets the background of this NPC.


        :param background: The background of this NPC.
        :type background: str
        """

        self._background = background

    @property
    def personality_traits(self) -> str:
        """Gets the personality_traits of this NPC.


        :return: The personality_traits of this NPC.
        :rtype: str
        """
        return self._personality_traits

    @personality_traits.setter
    def personality_traits(self, personality_traits: str):
        """Sets the personality_traits of this NPC.


        :param personality_traits: The personality_traits of this NPC.
        :type personality_traits: str
        """

        self._personality_traits = personality_traits

    @property
    def ideals(self) -> str:
        """Gets the ideals of this NPC.


        :return: The ideals of this NPC.
        :rtype: str
        """
        return self._ideals

    @ideals.setter
    def ideals(self, ideals: str):
        """Sets the ideals of this NPC.


        :param ideals: The ideals of this NPC.
        :type ideals: str
        """

        self._ideals = ideals

    @property
    def bonds(self) -> str:
        """Gets the bonds of this NPC.


        :return: The bonds of this NPC.
        :rtype: str
        """
        return self._bonds

    @bonds.setter
    def bonds(self, bonds: str):
        """Sets the bonds of this NPC.


        :param bonds: The bonds of this NPC.
        :type bonds: str
        """

        self._bonds = bonds

    @property
    def flaws(self) -> str:
        """Gets the flaws of this NPC.


        :return: The flaws of this NPC.
        :rtype: str
        """
        return self._flaws

    @flaws.setter
    def flaws(self, flaws: str):
        """Sets the flaws of this NPC.


        :param flaws: The flaws of this NPC.
        :type flaws: str
        """

        self._flaws = flaws
