# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class QuestRewards(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, experience_points: int=None, items: List[str]=None, gold: int=None):  # noqa: E501
        """QuestRewards - a model defined in Swagger

        :param experience_points: The experience_points of this QuestRewards.  # noqa: E501
        :type experience_points: int
        :param items: The items of this QuestRewards.  # noqa: E501
        :type items: List[str]
        :param gold: The gold of this QuestRewards.  # noqa: E501
        :type gold: int
        """
        self.swagger_types = {
            'experience_points': int,
            'items': List[str],
            'gold': int
        }

        self.attribute_map = {
            'experience_points': 'experiencePoints',
            'items': 'items',
            'gold': 'gold'
        }
        self._experience_points = experience_points
        self._items = items
        self._gold = gold

    @classmethod
    def from_dict(cls, dikt) -> 'QuestRewards':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Quest_rewards of this QuestRewards.  # noqa: E501
        :rtype: QuestRewards
        """
        return util.deserialize_model(dikt, cls)

    @property
    def experience_points(self) -> int:
        """Gets the experience_points of this QuestRewards.


        :return: The experience_points of this QuestRewards.
        :rtype: int
        """
        return self._experience_points

    @experience_points.setter
    def experience_points(self, experience_points: int):
        """Sets the experience_points of this QuestRewards.


        :param experience_points: The experience_points of this QuestRewards.
        :type experience_points: int
        """

        self._experience_points = experience_points

    @property
    def items(self) -> List[str]:
        """Gets the items of this QuestRewards.


        :return: The items of this QuestRewards.
        :rtype: List[str]
        """
        return self._items

    @items.setter
    def items(self, items: List[str]):
        """Sets the items of this QuestRewards.


        :param items: The items of this QuestRewards.
        :type items: List[str]
        """

        self._items = items

    @property
    def gold(self) -> int:
        """Gets the gold of this QuestRewards.


        :return: The gold of this QuestRewards.
        :rtype: int
        """
        return self._gold

    @gold.setter
    def gold(self, gold: int):
        """Sets the gold of this QuestRewards.


        :param gold: The gold of this QuestRewards.
        :type gold: int
        """

        self._gold = gold
